### ISSUE TITLE
Daemon crashes with Stretch

### ISSUE THREAD

**Issue by tillepille** [xkonni/raspberry-remote#28]
i recently upgraded my raspberry to Raspbian Stretch, but after that the daemon crashes pretty much once a day. 
Webserver works fine, after restarting the daemon it works also flawlessly.

Anyone else experiencing these problems or having an idea why this is?

I didnt try to setup a clean stretch, i would try this if no one else has these problems...

**Comment by LucaBernstein** [comment]
Did you find out why it crashed? What did you do about it to fix it? We encounter the same issue, where the daemon crashes "randomly"

Found the following in the logs from journalctl, stating the following:
```
Oct 15 12:07:02 some-123-wks daemon[20908]: message: 111111160
Oct 15 12:07:02 some-123-wks daemon[20908]: nSys: 1
Oct 15 12:07:02 some-123-wks daemon[20908]: nGroup: 11111
Oct 15 12:07:02 some-123-wks daemon[20908]: nSwitchNumber: 16
Oct 15 12:37:03 some-123-wks daemon[20908]: nActERROR on accept: Too many open files
Oct 15 12:37:03 some-123-wks daemon[20908]: ion: 0
Oct 15 12:37:03 some-123-wks daemon[20908]: nAddr: 1008
Oct 15 12:37:03 some-123-wks daemon[20908]: nPlugs: 1280
Oct 15 12:37:03 some-123-wks daemon[20908]: message: 111111160
[...]
Oct 15 12:37:03 some-123-wks daemon[20908]: message: 111111160
Oct 15 12:37:03 some-123-wks daemon[20908]: nSys: 1
Oct 15 12:37:03 some-123-wks daemon[20908]: nGroup: 11111
Oct 15 12:37:03 some-123-wks daemon[20908]: nSwitchNumber: 16
Oct 15 12:37:03 some-123-wks daemon[20908]: nAction: 0
Oct 15 12:37:03 some-123-wks daemon[20908]: nAddr: 1008
Oct 15 12:37:03 some-123-wks daemon[20908]: nPlugs: 1280
Oct 15 12:37:03 some-123-wks systemd[1]: bluelight_daemon.service: Main process exited, code=exited, status=1/FAILURE
Oct 15 12:37:03 some-123-wks systemd[1]: bluelight_daemon.service: Failed with result 'exit-code'.
```

When I restart the service so that it is running and send a command to the port with `echo -en "111111160"|nc -w 1 some-123-wks 11337` no log is created.

Have you any idea what creates those logs instead?

Thanks in advance, hope this is still relevant to you after nearly 2 years.

Luca
